[build]
  command = "npm ci --include=optional && npm install --no-save @rollup/rollup-linux-x64-gnu lightningcss-linux-x64-gnu && npm run build-only"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22.12.0"
